version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb_service
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:${MONGO_DATA_PATH:-/data/db}
    networks:
      - mail_network

  tcpserver:
    build:
      context: .
      dockerfile: backend/Dockerfile.tcpserver
    container_name: tcp_backend
    ports:
      - "${TCP_PORT:-5555}:5555"
    networks:
      - mail_network
    command: ["./server", "${TCP_PORT:-5555}", "16", "1"]

  apiserver:
    build:
      context: .
      dockerfile: api/Dockerfile.api
    container_name: api_server
    ports:
      - "${API_PORT:-3000}:3000"
    depends_on:
      - tcpserver
      - mongodb
    volumes:
      - ./api/uploads:/usr/api/uploads
    environment:
      TCP_SERVER_HOST: tcp_backend
      TCP_SERVER_PORT: ${TCP_PORT:-5555}
      MONGO_URL: mongodb://mongodb_service:${MONGO_PORT:-27017}
      PORT: ${API_PORT:-3000}
    networks:
      - mail_network
    command: ["node", "server.js"]

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.react
    container_name: frontend_app
    ports:
      - "${FRONTEND_PORT:-3001}:3001"
    depends_on:
      - apiserver
    environment:
      REACT_APP_API_URL: http://localhost:${API_PORT:-3000}
    networks:
      - mail_network
    command: ["serve", "-s", "build", "-l", "${FRONTEND_PORT:-3001}"]

volumes:
  mongo_data:

networks:
  mail_network:
    driver: bridge
