version: '3.8'

services:
  mongodb: 
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - internal

  tcpserver:
    build:
      context: .
      dockerfile: backend/Dockerfile.tcpserver
    ports:
      - "5555:5555"
    networks:
      - internal

  apiserver:
    volumes:
      - ./api/uploads:/usr/api/uploads

    build:
      context: .
      dockerfile: api/Dockerfile.api
    ports:
      - "3000:3000"
    depends_on:
      - tcpserver
      - mongodb         
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react 
    ports:
      - "3001:3001"
    depends_on:
      - apiserver
    networks:
      - internal

volumes:
  mongo-data:

networks:
  internal:
