FROM gcc:latest AS builder

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y cmake git && rm -rf /var/lib/apt/lists/*

COPY . .

RUN rm -rf build && mkdir build && cd build && cmake ../backend && make

FROM gcc:latest AS runtime

WORKDIR /app

RUN apt-get update && apt-get install -y python3 && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/app/build/server ./server

COPY backend/data ./data

RUN chmod +x ./server

CMD ["./server", "5555", "16", "1"]
