FROM node:18

WORKDIR /usr/api

# Install dependencies
COPY api/package*.json ./
RUN npm install

#  Copy env file into the container
COPY config/.env.local ./config/.env.local

# Copy the rest of the API
COPY api/ .

EXPOSE 3000
CMD ["node", "server.js"]
